server:
  #  port: ${random.int(5000,8000)}
  port: 8005
  servlet:
    context-path: /douyin
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: ticktock-comment
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camps_tiktok?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 18000000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: ${spring.application.name}

jwt:
  issuer: ticktock
  signed: VGlrVG9rCg==

mybatis:
  type-aliases-package: fun.witt.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: fun.witt.utils.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper:
#  helper-dialect: MYSQL
#  support-methods-arguments: true

logging:
  level:
    root: info
    fun.witt.mapper: debug
